### ISSUE TITLE
Few things broken

### ISSUE THREAD

**Issue by timothylevi** [learn-co-curriculum/fewpjs-document-onload#1]
* Lab can't be run after download by running `learn` or `learn test` in the terminal
  * User immediately receives an error `Cannot find module 'sinon'`
  * Even after running `npm -i` or `yarn` error persists
  * Same error running `npm test`
  * Running `npm install --save-dev sinon` and then `npm test`/`learn test`/`learn` solved the problem
* Typo "dome" -> "DOM"
* Unclear from README that "let's create a wrapper for this function called `domContentLoaded`" means we need to wrap the call to `addEventListener`
* Solution using `innerText` does not pass tests
```
function updateDOM() {
  document.getElementById('text').innerText = "This is really cool!"
}
```

**Comment by sgharms** [comment]
@timothylevi @maxwellbenton took a run at improving this and put up two new branches. Could you verify that they address your concerns and, if so, let him know that they're OK to merge (and we'll close this issue).

**Comment by timothylevi** [comment]
Thank you @sgharms . This looks great!
